using PRN232_EbayClone.Domain.Shared.Abstractions;
using PRN232_EbayClone.Domain.Shared.Results;

namespace PRN232_EbayClone.Domain.BuyerFeedback.Entities;

public class SellerBlacklist : AggregateRoot<Guid>
{
    public string SellerId { get; private set; } = string.Empty;
    public string BuyerId { get; private set; } = string.Empty;
    public string? Reason { get; private set; }
    public bool AutoGenerated { get; private set; }
    public bool IsActive { get; private set; }

    private SellerBlacklist() : base(Guid.Empty) { } // EF Core

    private SellerBlacklist(
        Guid id,
        string sellerId,
        string buyerId,
        string? reason,
        bool autoGenerated) : base(id)
    {
        SellerId = sellerId;
        BuyerId = buyerId;
        Reason = reason;
        AutoGenerated = autoGenerated;
        IsActive = true;
    }

    public static Result<SellerBlacklist> Create(
        string sellerId,
        string buyerId,
        string? reason,
        bool autoGenerated = false)
    {
        if (string.IsNullOrWhiteSpace(sellerId))
        {
            return Result.Failure<SellerBlacklist>(Error.Validation("SellerBlacklist.SellerId", "Seller ID is required"));
        }

        if (string.IsNullOrWhiteSpace(buyerId))
        {
            return Result.Failure<SellerBlacklist>(Error.Validation("SellerBlacklist.BuyerId", "Buyer ID is required"));
        }

        if (sellerId == buyerId)
        {
            return Result.Failure<SellerBlacklist>(Error.Validation("SellerBlacklist.SelfBlacklist", "Seller cannot blacklist themselves"));
        }

        var blacklist = new SellerBlacklist(Guid.NewGuid(), sellerId, buyerId, reason, autoGenerated);
        return Result.Success(blacklist);
    }

    public void Deactivate()
    {
        IsActive = false;
    }

    public void Reactivate(string? newReason = null)
    {
        IsActive = true;
        if (!string.IsNullOrEmpty(newReason))
        {
            Reason = newReason;
        }
    }

    public void UpdateReason(string? reason)
    {
        Reason = reason;
    }
}