/*
using MediatR;
using PRN232_EbayClone.Domain.Shared.Results;

namespace PRN232_EbayClone.Application.BuyerFeedback.Queries;

public record BlacklistedBuyerDto(
    Guid Id,
    string BuyerId,
    string BuyerName,
    string? Reason,
    bool AutoGenerated,
    DateTime CreatedAt
);

public record GetBlacklistedBuyersQuery(
    int Page = 1,
    int PageSize = 20
) : IRequest<Result<PagedResult<BlacklistedBuyerDto>>>;

public class GetBlacklistedBuyersQueryHandler : IRequestHandler<GetBlacklistedBuyersQuery, Result<PagedResult<BlacklistedBuyerDto>>>
{
    private readonly IApplicationDbContext _context;
    private readonly ICurrentUser _currentUser;

    public GetBlacklistedBuyersQueryHandler(IApplicationDbContext context, ICurrentUser currentUser)
    {
        _context = context;
        _currentUser = currentUser;
    }

    public async Task<Result<PagedResult<BlacklistedBuyerDto>>> Handle(GetBlacklistedBuyersQuery request, CancellationToken cancellationToken)
    {
        // Validate seller is authenticated
        if (string.IsNullOrEmpty(_currentUser.UserId))
        {
            return Result.Failure<PagedResult<BlacklistedBuyerDto>>(Error.Unauthorized("Seller must be authenticated"));
        }

        var query = _context.SellerBlacklists
            .Where(sb => sb.SellerId == _currentUser.UserId && sb.IsActive);

        // Get total count
        var totalCount = await query.CountAsync(cancellationToken);

        // Apply pagination and get results
        var blacklistedBuyers = await query
            .OrderByDescending(sb => sb.CreatedAt)
            .Skip((request.Page - 1) * request.PageSize)
            .Take(request.PageSize)
            .Select(sb => new BlacklistedBuyerDto(
                sb.Id,
                sb.BuyerId,
                _context.Users.Where(u => u.Id == sb.BuyerId).Select(u => u.FullName).FirstOrDefault() ?? "Unknown",
                sb.Reason,
                sb.AutoGenerated,
                sb.CreatedAt
            ))
            .ToListAsync(cancellationToken);

        var result = new PagedResult<BlacklistedBuyerDto>(
            blacklistedBuyers,
            totalCount,
            request.Page,
            request.PageSize
        );

        return Result.Success(result);
    }
}
*/